[ZP-36] Multithreaded interpreter closure
TinkoffCreditSystems/zeppelin pull request #10
Opened 2018-11-08 02:57 UTC by egorklimov

### What is this PR for?

This PR provides multithreading realization of interpreters closing.

Benchmark based on [JMH](http://openjdk.java.net/projects/code-tools/jmh/) - `ZeppelinServerBenchmarkTest`:
* Creates `InterpreterSettingManager` and `InterpreterFactory`;
* Runs 6 interpreters (`python`, `sh`, `md`, `groovy`, `angular`, `spark`) for each user in isolated mode;
* Measures InterpreterSettingManager closing.

Result with usersCnt - 7, 5, 3, 1 (42, 30, 18, 6 interpreter processes):
```
Benchmark                                                 (usersCnt)  Mode  Cnt   Score   Error  Units
ZeppelinServerBenchmarkTest.testDefaultServerShutdown              7  avgt   10  17,109 ± 0,567   s/op
ZeppelinServerBenchmarkTest.testDefaultServerShutdown              5  avgt   10  11,535 ± 0,028   s/op
ZeppelinServerBenchmarkTest.testDefaultServerShutdown              3  avgt   10   6,967 ± 0,062   s/op
ZeppelinServerBenchmarkTest.testDefaultServerShutdown              1  avgt   10   2,353 ± 0,021   s/op
ZeppelinServerBenchmarkTest.testServerShutdownInParallel           7  avgt   10   3,584 ± 0,220   s/op
ZeppelinServerBenchmarkTest.testServerShutdownInParallel           5  avgt   10   2,663 ± 0,233   s/op
ZeppelinServerBenchmarkTest.testServerShutdownInParallel           3  avgt   10   2,498 ± 0,178   s/op
ZeppelinServerBenchmarkTest.testServerShutdownInParallel           1  avgt   10   2,384 ± 0,022   s/op
```
[benchmark.zip](https://github.com/TinkoffCreditSystems/zeppelin/files/2560106/benchmark.zip) contains: 
* `Benchmark.patch` - patch with `ZeppelinServerBenchmarkTest` you could run test using ``;
* `benchmark.csv` - benchmark result;
![zepl-benchmark](https://user-images.githubusercontent.com/6136993/48150181-04b6da00-e2cf-11e8-8d11-979efb24dd58.png)
* `benchmark-result.json` - results (you could visualize it using [JMH Visualizer](http://jmh.morethan.io/))
![jmh-benchmark](https://user-images.githubusercontent.com/6136993/48150350-72fb9c80-e2cf-11e8-8bb5-de56e7fd1a38.png)

### How to run benchmark 
1. Apply patch from `benchmark.zip`
2. Add [IntelliJ IDEA JMH Plugin](https://plugins.jetbrains.com/plugin/7529-jmh-plugin)
3. Build Zeppelin 
4. Run ZeppelinServerBenchmarkTest in IntelliJ IDEA

### What type of PR is it?
Refactoring

### What is the Jira issue?
[ZP-36](https://jira.tcsbank.ru/browse/ZP-36)

### How should this be tested?
* CI pass

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

2018-11-14 07:02 UTC, aka-demik requested changes

2018-11-14 07:02 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/InterpreterSetting.java
> +            .peek(Thread::start)
Предлагаю добавить потокам UncaughtExceptionHandler с логгером.
```suggestion
            .peek(t -> t.setUncaughtExceptionHandler((th, e) ->
                LOGGER.error("InterpreterSetting close error", e)))
            .peek(Thread::start)
```

Мотивация простая, если в одном из `close()` вылетал не обработанный `Exception`, то раньше он подымался до самого [main()](https://github.com/TinkoffCreditSystems/zeppelin/blob/becfdf15f6cc80669fe70ae4443a21c807946827/zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java#L289-L298) и там попадал в лог. А в новой версии можем его потерять...

2018-11-14 10:02 UTC, egorklimov commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/InterpreterSetting.java
> +            .peek(Thread::start)
Поправил в 4bab30f76f302b30227d62377cd735bf1c723896.

2018-11-14 10:26 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/ManagedInterpreterGroup.java
> -      //TODO(zjffdu) move the close of schedule to Interpreter
Предлагаю todo сохранить. Мысль в ней дельная... Просто сдвинем в строку 169

2018-11-14 13:46 UTC, egorklimov commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/ManagedInterpreterGroup.java
> -      //TODO(zjffdu) move the close of schedule to Interpreter
Поправил в e7abdd305df86595c2c11f4743e7d9cbb0558206

2018-11-15 08:27 UTC, aka-demik approved these changes

2018-11-15 14:01 UTC, merged