[ZP-25] fix UI when paragraphs run sequential
TinkoffCreditSystems/zeppelin pull request #14
Opened 2018-11-12 13:44 UTC by Savalek

### What is this PR for?
This PR fixes the incorrect behavior of UI during the execution of the RunAllParagraphs. 
Including: allows you to copy the note at runtime (before that, the new note was created only after the end of runAllParagraph), blocks some interface elements.
The following items are blocked:

**Paragraphs Control :**
* Move up
* Move down
* Insert new
* Clone paragraph
* Run all above
* Run all below
* Disable run
* Remove

**Note :**
* Insert new paragraph

### What type of PR is it?
Improvement

### What is the Jira issue?
[Zeppelin-3095](https://issues.apache.org/jira/browse/ZEPPELIN-3095)
[ZP-25]

### GIF
![peek 2018-11-12 16-20](https://user-images.githubusercontent.com/30798933/48350794-511c6400-e699-11e8-952a-76a4dcc9e7b0.gif)

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

2018-11-15 16:02 UTC, aka-demik requested changes

2018-11-15 16:02 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/socket/Message.java
> +import java.util.Arrays;
```suggestion
```
Там codacy ругается на не используемый импорт. Предлагаю убрать...

2018-11-15 16:02 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/socket/Message.java
> +  private static final List<OP> sequentialRunExcludeMessageList = Arrays.asList(
We only doing search an element in a list. I think it's better to use HashSet here.
```suggestion
  private static final Set<OP> sequentialRunExcludeMessageList = new HashSet<>(Arrays.asList(
```

2018-11-15 16:02 UTC, aka-demik commented on zeppelin-server/src/main/java/org/apache/zeppelin/socket/NotebookServer.java
> +    try {
It may be better to move this try-finally in the NotebookService (line [389](https://github.com/TinkoffCreditSystems/zeppelin/blob/085efeb646f3a95b39bf555b5b04551119e3c0b9/zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java#L390-L405)). Together with the `changeSequentialRunStatus` function.

Motivation:
- fewer `getNote(noteId)` calls;
- the task of changing and sending statuses is more likely related to the service layer (NotebookService), rather than to the controller / UI layer (NotebookServer).

2018-11-15 16:02 UTC, aka-demik commented on zeppelin-web/src/app/notebook/notebook-actionBar.html
> +                ng-class="{'disabled':isNoteRunning()}"
Maybe
```suggestion
                ng-class="{'disabled':isSequentialRun()}"
```
or am I missing something?

2018-11-16 07:33 UTC, Savalek commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/socket/Message.java
> +import java.util.Arrays;
Так Array же используется в 198 строке. А codacy ругается на порядок импортов.

2018-11-16 07:35 UTC, Savalek commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/socket/Message.java
> +  private static final List<OP> sequentialRunExcludeMessageList = Arrays.asList(
done

2018-11-16 07:43 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/socket/Message.java
> +import java.util.Arrays;
Точно, не обратил внимания. В любом случае предложение пофиксить в силе :innocent:

2018-11-16 08:18 UTC, Savalek commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/socket/Message.java
> +import java.util.Arrays;
А есть какой-нибудь способ автоматически сортировать импорты по канонам codacy?
Idea сортирует по умолчанию так как сейчас залито.
Просто не очень хочется после каждого чиха сортировать ручками импорты :smiley:

2018-11-16 08:28 UTC, Savalek commented on zeppelin-web/src/app/notebook/notebook-actionBar.html
> +                ng-class="{'disabled':isNoteRunning()}"
isNoteRunning() Используется и в других кнопках в notebook-actionBar.html поэтому я решил не ставить здесь isSequentialRun(). С новым коммитом вообще уберу isSequentialRun из notebook.controller.js.

2018-11-16 08:52 UTC, Savalek commented on zeppelin-server/src/main/java/org/apache/zeppelin/socket/NotebookServer.java
> +    try {
я сначала так и собирался сделать, но в NotebookService не дергается ConnectionManager (Вообще он юзается только NotebokeServer). Поэтому решил не связывать их вместе (начитался "Совершенный код" по твоей рекомендации :smiley:).
Считаешь, что все же стоит перенести в NotebookService?

2018-11-16 10:02 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/socket/Message.java
> +import java.util.Arrays;
Ха... хороший вопрос. Я думал у IDEA и у codacy правила сортировки должны совпасть...

2018-11-16 11:20 UTC, aka-demik commented on zeppelin-server/src/main/java/org/apache/zeppelin/socket/NotebookServer.java
> +    try {
Глянул на `NotebookService`. Похоже, просто нужен будет отдельный рефакторинг.
Оставляем пока так.

2018-11-16 11:34 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/socket/Message.java
> +import java.util.Arrays;
В общем, у меня совпадает. Импортируй в настройки [Code style гугла](https://github.com/google/styleguide) файл [intellij-java-google-style.xml](https://github.com/google/styleguide/raw/gh-pages/intellij-java-google-style.xml). И IDEA будет сортировать правильно...
![default](https://user-images.githubusercontent.com/5939623/48619163-abc10300-e9ac-11e8-883b-926805c00015.png)

2018-11-16 11:39 UTC, Savalek commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/socket/Message.java
> +import java.util.Arrays;
Спасибо. Попробую.

2018-11-16 12:17 UTC, aka-demik requested changes

2018-11-16 12:17 UTC, aka-demik commented on zeppelin-web/src/app/notebook/notebook.controller.js
> +    $scope.info.isRunning = status;
Не нашел, а где потом используется этот `isRunning`?

2018-11-16 12:17 UTC, aka-demik commented on zeppelin-web/src/app/notebook/notebook.html
> +      <h4 class="plus-sign" ng-class="{'new-paragraph-disable': isSequentialRun()}">&#43; Add Paragraph</h4>
Ты же удалил `isSequentialRun`?

2018-11-16 12:17 UTC, aka-demik commented on zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js
> +    if (note && note.hasOwnProperty('info') &&
```diff
-    if (note && note.hasOwnProperty('info') &&
-      note.info.hasOwnProperty('isRunningSequentially') && note.info.isRunningSequentially === true) {
-      $scope.isNoteRunSequential = true;
-    } else {
-      $scope.isNoteRunSequential = false;
-    }
+    $scope.isNoteRunSequential = !!(note && note.hasOwnProperty('info')
+      && note.info.hasOwnProperty('isRunningSequentially')
+      && note.info.isRunningSequentially === true);
```
IDEA говорит, что так легче читается...

2018-11-16 12:17 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Note.java
> +    note.info.remove("isRunningSequentially");
Я тут подумал, если при вычитке мы это поле удаляем, т.е. фактически храним его только в ОЗУ...
Может сделать его обычным `transient` полем как [эти](https://github.com/TinkoffCreditSystems/zeppelin/blob/f402cce41ae52afe62c341a1247e33ff864b8293/zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Note.java#L88-L94).
Зачем нам эти приседания с `infoMap` и кастами в `boolean`?

2018-11-16 12:35 UTC, Savalek commented on zeppelin-web/src/app/notebook/notebook.html
> +      <h4 class="plus-sign" ng-class="{'new-paragraph-disable': isSequentialRun()}">&#43; Add Paragraph</h4>
:man_facepalming: no comments

2018-11-16 12:52 UTC, Savalek commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Note.java
> +    note.info.remove("isRunningSequentially");
Тоже думал)
Но `transient` не перекидываются по вебсокету, когда грузишь ноут.
И надо тогда на клиенте еще какие-то запросы посылать на проверку выполняется/не выполняется.
А мапа с `info` мне показалось по логике как раз подходит.

2018-11-16 12:52 UTC, Savalek commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Note.java
> +    note.info.remove("isRunningSequentially");
Приму любый возражения)

2018-11-19 13:10 UTC, aka-demik approved these changes

2018-11-19 13:28 UTC, aka-demik requested changes
Тут в upstream'е вопрос задали...
> 1. What happens if a browser opens running notebook? Is it correct that SEQUENTIAL_RUN_STATUS message will not be received in this case. Can we handle this case?
> 2. How is it going to behave when notebook run is triggered by cron scheduler?

По первому вопросу, как я понимаю, всё ок. Значение будет заполнено и первый раз вычитается [тут](https://github.com/TinkoffCreditSystems/zeppelin/pull/14/files/ebbf21a46252d2eeef032bb827b0a529968be165#diff-52fa6628f0b6793d22ffe1f3e4763635R153). Или нет?

А по второму вопросу, Lee moon soo, кажется прав. Планировщик при запуске плевать хотел на сервис и [дергает прямо ноут ](https://github.com/TinkoffCreditSystems/zeppelin/blob/085efeb646f3a95b39bf555b5b04551119e3c0b9/zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java#L563). Соответственно, про то что он запущен, фронт не узнает. А запуск по крону, думаю, стоит считать `isNoteRunSequential`.

2018-11-26 08:41 UTC, aka-demik commented on zeppelin-web/src/app/notebook/notebook-actionBar.html
> +                ng-class="{'disabled':isNoteRunning()}"
Теперь везде переменная, а тут остался вызов функции.

2018-11-26 08:41 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
> +    public synchronized void runAll(Note note) {
`synchronized` чтобы шедулер не запустил задачу снова до того как отработает предыдущий запуск?

2018-11-26 08:41 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/socket/Message.java
> +  private static final Set<OP> disabledForRunningNoteMessages = new HashSet<>(Arrays.asList(
Совсем забыл.
Мы же читаем это из разных потоков. Чтобы всё было честно, нужно завернуть его в `Collections.unmodifiableSet()`

2018-11-26 08:50 UTC, Savalek commented on zeppelin-web/src/app/notebook/notebook-actionBar.html
> +                ng-class="{'disabled':isNoteRunning()}"
`isNoteRunning()` - функция из `notebook.controller.js`.
`isNoteRunning` - переменная в `paragraph.controller.js`.
У них разная зона видимости.

2018-11-26 08:53 UTC, Savalek commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
> +    public synchronized void runAll(Note note) {
Я просто скопировал этоn метод целиком :smiley:.
В таком виде смысла в `synchronized` я не вижу.
Уберу его.

2018-11-26 08:53 UTC, Savalek commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/socket/Message.java
> +  private static final Set<OP> disabledForRunningNoteMessages = new HashSet<>(Arrays.asList(
:ok_hand:

2018-11-26 14:55 UTC, aka-demik approved these changes

2018-11-26 15:27 UTC, aka-demik commented
Merged in #22

2018-11-26 15:27 UTC, closed without merging