[ZP-64] Add Quartz dynamic thread pool & REST API functionality for quartz configuration
TinkoffCreditSystems/zeppelin pull request #20
Opened 2018-11-23 09:41 UTC by egorklimov

### What is this PR for?
It would be nice if we could change thread pool size for scheduler dynamically.

### Using this feature:
1. Create file `quartz.properties` from default file located in `org.quartz` and add them to `conf` directory
3. In `quartz.properties` set `org.quartz.threadPool.class` to `org.apache.zeppelin.scheduler.dynamic_pool.impl.DynamicThreadPoolExecutor`

Otherwise you will get message "Thread pool size is constant."

### What type of PR is it?
Improvement

### What is the Jira issue?
[ZP-64]
[ZP-47]

### How should this be tested?
* Tests added
* Tested manually
* CI pass

### Screenshots
Firstly, when thread pool size equals `1` notes wait for each other, but when scheduler thread pool size changed to `2` they start to work in parallel.

![cron mp4](https://user-images.githubusercontent.com/6136993/43912629-77707ad4-9c0b-11e8-9d6c-62cbc67568a8.gif)

### Questions:
* Does the licenses files need update?  No
* Is there breaking changes for older versions? No
* Does this needs documentation? Yes, REST API docs updated

2018-11-23 11:57 UTC, aka-demik requested changes

2018-11-23 11:57 UTC, aka-demik commented on zeppelin-server/src/test/java/org/apache/zeppelin/rest/AbstractTestRestApi.java
> +        System.setProperty("org.quartz.properties", "./quartz.properties");
Однажды заполненное значение остаётся для всех остальных тестов. Нужно где-то сбрасывать.

2018-11-24 08:49 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
> +  private StdSchedulerFactory quartzSchedFact;
Давай это поле вообще уберём?
Не вижу смысла хранить эту Factory...

2018-11-25 16:56 UTC, egorklimov commented on zeppelin-server/src/test/java/org/apache/zeppelin/rest/AbstractTestRestApi.java
> +        System.setProperty("org.quartz.properties", "./quartz.properties");
Вынес из `AbstractTestRestApi` в [`AdminRestApiTest#init`](https://github.com/TinkoffCreditSystems/zeppelin/pull/20/files#diff-265d7bb8d6418e32f123b831ea4caec9R40), сбрасываю значение в [`AdminRestApiTest#destroy`](https://github.com/TinkoffCreditSystems/zeppelin/pull/20/files#diff-265d7bb8d6418e32f123b831ea4caec9R46)

2018-11-25 16:58 UTC, egorklimov commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
> +  private StdSchedulerFactory quartzSchedFact;
Исправил в 7191b6c67d377e62363eff4b4ea39c1522d60781

2018-11-27 08:58 UTC, aka-demik requested changes

2018-11-27 08:58 UTC, aka-demik commented on docs/usage/other_features/cron_scheduler.md
> +      <td>```org.quartz.threadPool.class```</td>
Looks like ``` is not working. Maybe it's better to use `?
But most likely, the markdown inside the html-tag does not work.

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-server/src/main/java/org/apache/zeppelin/rest/AdminRestApi.java
> -  private static final Logger logger = LoggerFactory.getLogger(AdminRestApi.class);
А зачем перемещаем строку? Если не примут, лишний diff.

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-server/src/main/java/org/apache/zeppelin/rest/AdminRestApi.java
> -  private static final Logger logger = LoggerFactory.getLogger(AdminRestApi.class);
К стати, по большинству файлов нет пустой строки между классом и первым полем.

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +      new ThreadPoolExecutor(1, 1, 1, TimeUnit.MINUTES, new SynchronousQueue<>());
Умолчание же 10, по документации?
```suggestion
      new ThreadPoolExecutor(1, 10, 1, TimeUnit.MINUTES, new SynchronousQueue<>());
```

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +  private ThreadPoolExecutor executor =
```suggestion
  private final ThreadPoolExecutor executor =
```
Иначе другим потокам не гарантирована видимость `executor`-а, после инициализации.

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +  private static final Object poolEvent = new Object();
```suggestion
  private Object poolEvent = new Object();
```
poolEvent же синхронизирует работу с конкретным `executor`. Думаю, его нет смысла расширять на все экземпляры пула.

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +  private int threadCount;
```suggestion
```
Предлагаю убрать и место переменной ходить прямо в `executor.getMaximumPoolSize()`. Тем более, что в таком виде метод `setThreadCount` не потокобезопасен. Его можно упростить до вызова `executor.setMaximumPoolSize(threadCount)` с проверкой на `IllegalArgumentException`.

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +    if (schedulerInstanceId != null && INSTANCES.get(schedulerInstanceId) != this) {
Не совсем понял смысл.
Если это для подчистки старых значений при вызове `setInstanceId` несколько раз с разным `schedInstId`, то предлагаю так:
```java
  @Override
  public void setInstanceId(String schedInstId) {
    if (schedulerInstanceId != null) {
      INSTANCES.remove(schedulerInstanceId, this);
    }
    schedulerInstanceId = schedInstId;
    if (schedulerInstanceId != null) {
      INSTANCES.put(schedulerInstanceId, this);
    }
  }
```
Если я не правильно понял, то расскажи :innocent:

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +  private int priority = Thread.NORM_PRIORITY;
```suggestion
  private volatile int priority = Thread.NORM_PRIORITY;
```
Так как мы её [читаем из другого потока](https://github.com/TinkoffCreditSystems/zeppelin/blob/f1c82743ed46c560d54941346d987a3c73f8c630/zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java#L242)

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +  public int getThreadPriority() {
Мне кажется, этот `getThreadPriority` не используется.

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +  public String getThreadNamePrefix() {
Кмк, этот `getThreadNamePrefix` не используется.

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +  public void setKeepAliveTime(long time, TimeUnit timeUnit) {
Этот сеттер не будет работать через property-конфиг. У них там очень примитивная рефлексия:
```java
                Class<?>[] params = setMeth.getParameterTypes();
                if (params.length != 1) {
                    throw new NoSuchMethodException(
                        "No 1-argument setter for property '" + name + "'");
                }
```
org/quartz-scheduler/quartz/2.2.1/quartz-2.2.1-sources.jar!/org/quartz/impl/StdSchedulerFactory.java:1411

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +      newThread.setName(String.format(nameFormat, count.getAndIncrement()));
Мне кажется, лучше перестраховаться и сделать так:
```suggestion
      newThread.setName(String.format("%s-%d", threadNamePrefix, count.getAndIncrement()));
```
Иначе, если какой-нибудь умник укажет в конфиге `threadNamePrefix = %s` мы словим Exception. Ну и вообще, user input в шаблон String.format лучше не пускать :innocent:

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +      LOGGER.info("Thread - {} created", newThread.toString());
```suggestion
      LOGGER.info("Thread - {} created", newThread);
```
`toString` не нужен, логгер его сам вызывает, причём в null-safe варианте.

2018-11-27 08:58 UTC, aka-demik commented on zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/SchedulerConfigRequest.java
> +public class SchedulerConfigRequest {
Судя по остальным классам в `org.apache.zeppelin.rest.message` тут нужен:
```suggestion
public class SchedulerConfigRequest implements JsonSerializable {
```

2018-11-27 11:09 UTC, aka-demik requested changes

2018-11-27 11:09 UTC, aka-demik commented on zeppelin-server/src/main/java/org/apache/zeppelin/rest/AdminRestApi.java
> +  @Path("cron/pool/{id}/poolSize")
Решили же просто 
```suggestion
  @Path("cron/pool/{id}")
```
Так как `poolSize` будет полем внутри запроса.

2018-11-27 11:09 UTC, aka-demik commented on zeppelin-server/src/main/java/org/apache/zeppelin/rest/AdminRestApi.java
> +      AdminService.setSchedulerThreadPoolSize(schedulerId, request.getPoolSize());
Тут нужно либо проверять `request.getPoolSize()` на null, если он сделан обёрткой чтобы быть "не обязательным полем". Либо сделать его обязательным и примитивом.

2018-11-27 11:09 UTC, aka-demik commented on zeppelin-server/src/main/java/org/apache/zeppelin/rest/AdminRestApi.java
> +  public Response getQuartzSchedulerPoolInfo() {
Я думал, мы тут вернём список шедулеров. А то получается что в `changeSchedulerPoolSize` мы редактируем по id, а считать можем только один.
Думаю, стоит сделать вместо класса `SchedulerConfigRequest` класс `SchedulerConfigMessage` со всеми нужными полями и возвращать уже `List<SchedulerConfigMessage>`. А `changeSchedulerPoolSize` переименовать в `changeScheduler` и использовать там тот же `SchedulerConfigMessage` в качестве входа.

2018-11-27 11:09 UTC, aka-demik commented on zeppelin-server/src/main/java/org/apache/zeppelin/rest/AdminRestApi.java
> +          Response.Status.INTERNAL_SERVER_ERROR,
Судя по наличию [WebApplicationExceptionMapper'a](https://github.com/TinkoffCreditSystems/zeppelin/blob/0d746fa2e2787a661db70d74035120ae3516ace3/zeppelin-server/src/main/java/org/apache/zeppelin/rest/exception/WebApplicationExceptionMapper.java#L28-L44) в ручной выдаче INTERNAL_SERVER_ERROR нет необходимости.

2018-11-27 11:09 UTC, aka-demik commented on zeppelin-server/src/main/java/org/apache/zeppelin/service/AdminService.java
> +  public static String getSchedulerName() throws SchedulerException {
Мне кажется, `getSchedulerName`, `getSchedulerId`, `getSchedulerPoolSize`, `getSchedulerThreadPoolClass` и `getSchedulerJobStoreClass` не стоит выделять как отдельные public методы. Лучше просто в одном методе вернуть `SchedulerConfigMessage` со всеми заполненными полями.

2018-11-27 11:09 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
> +    quartzSched = quartzSchedFact.getScheduler();
```suggestion
    quartzSched = new StdSchedulerFactory().getScheduler();
```
Проще, короче, но не существенно. Так в рамках красоты =)

2018-11-27 11:09 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
> +  public Scheduler getQuartzSched() {
Для тестов достаточно оставить package private, как и было у `quartzSched`. `public` лучше не давать. Оставишь, обязательно кто-нибудь полезет =)

2018-11-27 11:09 UTC, aka-demik commented on zeppelin-zengine/src/test/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPoolTest.java
> +  public void testConcurrentExecution() throws SchedulerConfigException {
Есть мысль как написать этот тест так, чтобы он не ждал секунду, но проверял тот же контракт :wink: 
Расскажу в слаке...

2018-11-27 14:21 UTC, egorklimov commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
> +  public Scheduler getQuartzSched() {
Это я в угоду Codacy решил исправить)

2018-11-27 14:24 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
> +  public Scheduler getQuartzSched() {
А он ругался на отсутствие геттера или на package private?
Кинь ссылку если осталась. Интересно же...

2018-11-27 14:26 UTC, egorklimov commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +  public void setKeepAliveTime(long time, TimeUnit timeUnit) {
Поэтому не вынес его в документацию, но почему-то решил на всякий случай оставить

2018-11-27 14:30 UTC, egorklimov commented on docs/usage/other_features/cron_scheduler.md
> +      <td>```org.quartz.threadPool.class```</td>
Сам не понимаю почему так, но в других доках по ресту аналогично сделано, например [Interpreter REST API](https://github.com/TinkoffCreditSystems/zeppelin/blob/f1c82743ed46c560d54941346d987a3c73f8c630/docs/usage/rest_api/interpreter.md)

2018-11-27 14:31 UTC, egorklimov commented on zeppelin-server/src/main/java/org/apache/zeppelin/rest/AdminRestApi.java
> -  private static final Logger logger = LoggerFactory.getLogger(AdminRestApi.class);
Решил попросить идею отформатировать код после того как гугловский кодстайл поставил :innocent:

2018-11-27 14:33 UTC, egorklimov commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +      new ThreadPoolExecutor(1, 1, 1, TimeUnit.MINUTES, new SynchronousQueue<>());
Если я не ошибаюсь, `org.quartz.threadPool.threadCount` обязательный параметр, поэтому он будет в любом случае перезаписан, но на всякий случай можно поставить 10.

2018-11-28 06:50 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +  public void setKeepAliveTime(long time, TimeUnit timeUnit) {
Ааа...
Предлагаю назвать `setKeepAliveTimeSec` и оставить в параметрах только первый `int`.
Тогда конфиг через рефлексию заработает
Ну  и можно тогда в документацию будет добавить.

2018-11-28 06:53 UTC, aka-demik commented on docs/usage/other_features/cron_scheduler.md
> +      <td>```org.quartz.threadPool.class```</td>
Я, собственно, потому и пытался собрать сайт джекилом.
Посмотреть что будет. Так как на сайте [всё ок](https://zeppelin.apache.org/docs/0.9.0-SNAPSHOT/usage/rest_api/interpreter.html)
Но локальная сборка сайта падает по зависимостям =(

2018-11-28 08:28 UTC, aka-demik commented on zeppelin-server/src/main/java/org/apache/zeppelin/rest/AdminRestApi.java
> -  private static final Logger logger = LoggerFactory.getLogger(AdminRestApi.class);
О!
> A blank line before the first member or initializer, or after the last member or initializer of the class, is neither encouraged nor discouraged. 

Стандарту всё равно. В настройках нет опции "не трогай", поставили 1.
![default](https://user-images.githubusercontent.com/5939623/49138497-58ca4280-f300-11e8-9a2a-390cb2aedf23.png)

Вилы...
Автоформат будет ставить, большая часть кодовой базы не ставит =(
Я за то чтобы поставить 0 и не плодить лишний diff. Но в целом не принципиально.

2018-11-28 08:30 UTC, aka-demik commented on zeppelin-server/src/main/java/org/apache/zeppelin/rest/AdminRestApi.java
> -  private static final Logger logger = LoggerFactory.getLogger(AdminRestApi.class);
> Решил попросить идею отформатировать код после того как гугловский кодстайл поставил innocent

А вообще, это хорошо =)

2018-11-28 08:43 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +      new ThreadPoolExecutor(1, 1, 1, TimeUnit.MINUTES, new SynchronousQueue<>());
Он обязательный для `SimpleThreadPool`, ибо его так написали...
А тут нам самим решать. Мне кажется, проще оставить умолчание прямо в коде и позволить менять через файл.
Для конечного пользователя нет разницы дефолтный `/org/quartz/quartz.properties` зашитый в jar, или константа у нас "в конструкторе"...

2018-11-28 08:45 UTC, aka-demik commented on docs/usage/other_features/cron_scheduler.md
> +      <td>```org.quartz.threadPool.class```</td>
Оставим пока так. Может и не правильно, зато одинаково.

2018-11-28 10:09 UTC, egorklimov commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
> +  public Scheduler getQuartzSched() {
На package private, но ссылка не сохранилась(

2018-11-30 13:28 UTC, aka-demik submitted a review, later dismissed

2018-11-30 13:28 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +      newThread.setUncaughtExceptionHandler((th, e) -> LOGGER.error("ThreadPool error", e));
Я бы сказал, что это 
```suggestion
      newThread.setUncaughtExceptionHandler((th, e) -> LOGGER.error("Unexpected cron job error", e));
```
у пула-то всё хорошо. А вот job упал.

2018-11-30 13:28 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +  private String threadNamePrefix;
```suggestion
  private volatile String threadNamePrefix;
```
Из-за [DynamicThreadPool.DynamicThreadFactory#newThread](https://github.com/TinkoffCreditSystems/zeppelin/blob/c90cf0416466d959d2b9df525351c326690f2906/zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java#L216)

2018-11-30 13:28 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +  private String schedulerInstanceId;
```suggestion
  private volatile String schedulerInstanceId;
```
Из-за [DynamicThreadPool#shutdown](https://github.com/TinkoffCreditSystems/zeppelin/blob/c90cf0416466d959d2b9df525351c326690f2906/zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java#L150)

2018-11-30 13:28 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +  private String schedulerInstanceId;
Можно и `schedulerInstanceName` за компанию. Хотя, формальных причин для этого нет.

2018-11-30 13:28 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +    private Runnable job;
Maybe?
```suggestion
    private final Runnable job;
```

2018-11-30 13:28 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +    if (!waitForJobsToComplete) {
```suggestion
    if (waitForJobsToComplete) {
```
Перепутана логика `waitForJobsToComplete`.

2018-11-30 13:28 UTC, aka-demik commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +      LOGGER.error(e.toString());
```suggestion
      LOGGER.error("Cron job rejected by thread pool", e);
```
Чаще всего, не стоит в логгер передавать `toString`. В крайнем случае если нечего сказать в сообщении и нужен только Exception, то
```java
LOGGER.error("", e);
```

2018-11-30 13:48 UTC, egorklimov commented on zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
> +    if (!waitForJobsToComplete) {
Упс, это я так `executor.shutdownNow()` тестил и забыл вернуть :man_facepalming:

2018-12-05 13:17 UTC, Savalek commented
LGTM

2018-12-05 13:18 UTC, Savalek submitted a review, later dismissed

2018-12-13 21:48 UTC, c47harsis commented on zeppelin-server/src/main/java/org/apache/zeppelin/rest/AdminRestApi.java
> +      if (request.getPoolSize() != null) {
Может быть вынести if за пределы try..catch?

2018-12-17 07:36 UTC, Savalek submitted a review, later dismissed

2019-01-31 09:15 UTC, merged