[ZP-103] Refactor `ConnectionManager` to avoid dead-lock
TinkoffCreditSystems/zeppelin pull request #32
Opened 2019-01-21 13:06 UTC by egorklimov

### What is this PR for?
Refactor `ConnectionManager` to avoid dead-lock

### What type of PR is it?
Bug Fix & Refactoring

### What is the Jira issue?
* ZP-103

### How should this be tested?
* CI pass
* Tests updated

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

2019-01-30 07:30 UTC, Savalek requested changes

2019-01-30 07:30 UTC, Savalek commented on zeppelin-server/src/main/java/org/apache/zeppelin/socket/ConnectionManager.java
> +      LOGGER.debug("Remove connection {} from note: {}", socket, noteId);
Мне кажется здесь лучше проверять удалено ли, а потом только логировать.

2019-01-30 07:30 UTC, Savalek commented on zeppelin-server/src/main/java/org/apache/zeppelin/socket/ConnectionManager.java
> +    boolean collaborativeStatusNew = !socketList.isEmpty();
Всё же я бы оставил `size() > 1`, а то так он всегда будет включен.

2019-01-30 07:30 UTC, Savalek commented on zeppelin-server/src/main/java/org/apache/zeppelin/socket/ConnectionManager.java
> +  public void broadcast(String noteId, Message m, NotebookSocket exclude) {
В этом классе уже есть метод `broadcastExcept`)

2019-01-30 07:30 UTC, Savalek commented on zeppelin-server/src/main/java/org/apache/zeppelin/socket/ConnectionManager.java
> +  public void broadcast(String noteId, Message m, NotebookSocket exclude) {
А, ты его убрал.
Сорри не до конца посмотрел)

2019-01-31 12:42 UTC, egorklimov commented on zeppelin-server/src/main/java/org/apache/zeppelin/socket/ConnectionManager.java
> +      LOGGER.debug("Remove connection {} from note: {}", socket, noteId);
Исправил в a97b2bc9dde315b77d24869afc1cef8b4d8aa9fb.

2019-01-31 12:42 UTC, egorklimov commented on zeppelin-server/src/main/java/org/apache/zeppelin/socket/ConnectionManager.java
> +    boolean collaborativeStatusNew = !socketList.isEmpty();
Исправил в a97b2bc9dde315b77d24869afc1cef8b4d8aa9fb.

2019-02-05 08:00 UTC, D01B approved these changes
вроде норм. надо будет протестировать

2019-02-05 15:10 UTC, merged